# service: paylands-shop

# provider:
#   name: aws
#   runtime: nodejs18.x
#   stage: prod
#   region: eu-west-1

# functions:
#   app:
#     handler: lambda.handler
#     events:
#       - http:
#           path: /proxy
#           method: POST

# plugins:
#   - serverless-dotenv-plugin
#   - serverless-s3-sync

# custom:
#   dotenv:
#     basePath: ./
#   s3Sync:
#     - bucketName: paylands-shop-prod
#       localDir: public
#       deleteRemoved: true

# resources:
#   Resources:
#     StaticAssetsBucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: paylands-shop-prod
#       DeletionPolicy: Retain
#   Outputs:
#     StaticAssetsBucketName:
#       Value: !Ref StaticAssetsBucket
#       Export:
#         Name: StaticAssetsBucketName
